package io.github.posaydone.filmix.core.model

data class HistoryShow(
    val id: Int,
    val title: String,
    val poster: String,
    val isSeries: Boolean,
    val description: String,
    val thumbnail: String?,
    val watchedSeconds: Int?,
    val durationSeconds: Int?,
    val seasonNumber: Int?,
    val episodeNumber: Int?,
    val episodeTitle: String?,
    val watchedAtSeconds: Long? = null,
    val backdropUrl: String? = null,
    val genres: List<String> = emptyList(),
    val countries: List<String> = emptyList(),
    val ratingKp: Double? = null,
    val ratingImdb: Double? = null,
    val votesKp: Int? = null,
    val year: Int = 0,
    val movieLength: Int? = null,
)

fun HistoryShow.toShow(): Show = Show(
    id = id,
    last_episode = null,
    last_season = null,
    original_name = title,
    poster = thumbnail?.takeIf { it.isNotBlank() } ?: poster,
    backdropUrl = backdropUrl ?: "",
    quality = "",
    status = null,
    title = title,
    votesNeg = 0,
    votesPos = 0,
    year = year,
    url = "",
    description = description,
    genres = genres,
    countries = countries,
    ratingKp = ratingKp,
    ratingImdb = ratingImdb,
    votesKp = votesKp,
    movieLength = movieLength,
)
