name: Build TV and Mobile App

on:
    push:
        branches: [main, master]

env:
    KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
    RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

jobs:
    build_apk_aab:
        if: startsWith(github.head_ref, 'release/') == true || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        name: Build release artifacts
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4

            - name: Set current date as env variable
              run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

            - name: Set repository name as env variable
              run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

            - name: Set Up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: "zulu" # See 'Supported distributions' for available options
                  java-version: "17"
                  cache: "gradle"

            - name: Checkout keystore repo
              uses: actions/checkout@v2
              with:
                  repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
                  token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
                  path: app/keystore

            - name: Run tests and build release artifacts for mobile
              run: |
                  ./gradlew mobile:assembleRelease --stacktrace
                  ./gradlew mobile:bundleRelease

            - name: Run tests and build release artifacts for tv
              run: |
                  ./gradlew tv:assembleRelease --stacktrace
                  ./gradlew tv:bundleRelease

            - name: Upload mobile signed APK
              uses: actions/upload-artifact@v4
              with:
                  name: app-release.apk
                  path: app/mobile/build/outputs/apk/release/mobile-release.apk

            - name: Upload TV signed APK
              uses: actions/upload-artifact@v4
              with:
                  name: app-release.apk
                  path: app/tv/build/outputs/apk/release/tv-release.apk
