name: Build TV and Mobile App

env:
    mobile_project_module: app:mobile
    tv_project_module: app:tv
    KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
    RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

on:
    push:
        branches: [main, master]

jobs:
    build_apk_aab:
        if: startsWith(github.head_ref, 'release/') == true || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        name: Build release artifacts
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4

            - name: Set current date as env variable
              run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

            - name: Set repository name as env variable
              run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

            - name: Set Up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: "zulu" # See 'Supported distributions' for available options
                  java-version: "17"
                  cache: "gradle"

            - name: Checkout keystore repo
              uses: actions/checkout@v2
              with:
                  repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
                  token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
                  path: app/keystore

            - name: Change wrapper permissions
              run: chmod +x ./gradlew

            # Run Tests Build
            - name: Run gradle tests
              run: ./gradlew test

            # Run Build Project
            - name: Build gradle project
              run: ./gradlew build

            - name: Build apk release project (APK) - ${{ env.main_project_module }} module
              run: ./gradlew assemble

            - name: Upload Mobile APK Release - ${{ env.repository_name }}
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) release generated
                  path: ${{ env.mobile_project_module }}/build/outputs/apk/release/

            - name: Upload TV APK Release - ${{ env.repository_name }}
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) release generated
                  path: ${{ env.tv_project_module }}/build/outputs/apk/release/
